setwd("C:/Users/betty/Desktop/coursera/exploratory data analysis/week-1")
HousePowerConsumption <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", stringsAsFactors = FALSE)
usedata <- HousePowerConsumption[HousePowerConsumption$Date %in% c("1/2/2007","2/2/2007") ,]
globalactivepower <- as.numeric(usedata$Global_active_power)
datetime <- strptime(paste(usedata$Date, usedata$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
voltage <- as.numeric(usedata$Voltage)
globalreactivepower <- as.numeric(usedata$Global_reactive_power)

subMetering1 <- as.numeric(usedata$Sub_metering_1)
subMetering2 <- as.numeric(usedata$Sub_metering_2)
subMetering3 <- as.numeric(usedata$Sub_metering_3)

png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(datetime, globalactivepower, type="l", xlab="", ylab="Global Active Power")
plot(datetime, voltage, type="l", xlab="datetime", ylab="Voltage")
plot(datetime, subMetering1, type="l", ylab="Energy Submetering")
lines(datetime, subMetering2, type="l", col="red")
lines(datetime, subMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(datetime, globalreactivepower, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
